name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Add .env
        run: |
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

      - name: Copy files to EC2
        run: scp -o StrictHostKeyChecking=no -r ./* ${{vars.EC2_NAME_AT_IP}}:${{vars.EC2_PROJECT_PATH}}

      - name: Run deployment commands
        run: ssh -o StrictHostKeyChecking=no ${{vars.EC2_NAME_AT_IP}} "cd ${{vars.EC2_PROJECT_PATH}} && bash setup-ec2.bash deploy"
