name: Start EC2 Instance

on:
  workflow_dispatch:

jobs:
  start:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Start EC2 Instance
        run: |
          aws ec2 start-instances --instance-ids ${{ vars.EC2_INSTANCE_ID }} --region ${{ vars.AWS_REGION }}

      - name: Get EC2 Public IP
        id: fetch_ip # ID를 설정하여 이후 스텝에서 참조 가능
        run: |
          PUBLIC_IP=$(aws ec2 describe-instances \
            --instance-ids ${{ vars.EC2_INSTANCE_ID }} \
            --query "Reservations[*].Instances[*].PublicIpAddress" \
            --output text \
            --region ${{ vars.AWS_REGION }})
          echo "PUBLIC_IP=$PUBLIC_IP" >> $GITHUB_ENV  # GitHub 환경 변수로 설정

      - name: Update vars.EC2_NAME_AT_IP
        env:
          PUBLIC_IP: ${{ env.PUBLIC_IP }}
        run: |
          curl -X PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GHCR_PAT }}" \
            https://api.github.com/repos/obov/my-chatbot/actions/variables/EC2_NAME_AT_IP \
            -d "{\"value\":\"$PUBLIC_IP\"}"

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

      - name: Setup After Start
        run: ssh -o StrictHostKeyChecking=no ${{ vars.EC2_NAME_AT_IP }} "cd ${{vars.EC2_PROJECT_PATH}} && bash setup-ec2.bash start"
