name: Start EC2 Instance

on:
  workflow_dispatch:

jobs:
  start:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Start EC2 Instance
        run: |
          aws ec2 start-instances --instance-ids ${{ vars.EC2_INSTANCE_ID }} --region ${{ vars.AWS_REGION }}

      - name: Get EC2 Public IP
        id: fetch_ip # ID를 설정하여 이후 스텝에서 참조 가능
        run: |
          PUBLIC_IP=$(aws ec2 describe-instances \
            --instance-ids ${{ vars.EC2_INSTANCE_ID }} \
            --query "Reservations[*].Instances[*].PublicIpAddress" \
            --output text \
            --region ${{ vars.AWS_REGION }})
          echo "PUBLIC_IP=$PUBLIC_IP" >> $GITHUB_ENV  # GitHub 환경 변수로 설정

      - name: Update vars.EC2_NAME_AT_IP
        env:
          PUBLIC_IP: ${{ env.PUBLIC_IP }}
        run: |
          curl -X PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GHCR_PAT }}" \
            https://api.github.com/repos/obov/my-chatbot/actions/variables/EC2_NAME_AT_IP \
            -d "{\"value\":\"ubuntu@${{env.PUBLIC_IP}} \"}"

      - name: Update Route53 Record
        env:
          PUBLIC_IP: ${{ env.PUBLIC_IP }}
          HOSTED_ZONE_ID: ${{ vars.ROUTE53_HOSTED_ZONE_ID }} # Route 53의 호스팅 영역 ID
          DOMAIN_NAME: ${{ vars.ROUTE53_DOMAIN }} # 업데이트할 도메인 이름
        run: |
          echo '{
          "Comment": "Update record to new IP address",
          "Changes": [
              {
              "Action": "UPSERT",
              "ResourceRecordSet": {
                  "Name": "'${DOMAIN_NAME}'",
                  "Type": "A",
                  "TTL": 300,
                  "ResourceRecords": [
                  {
                      "Value": "'${PUBLIC_IP}'"
                  }
                  ]
              }
              }
          ]
          }' > change-resource-record-sets.json

          aws route53 change-resource-record-sets \
          --hosted-zone-id $HOSTED_ZONE_ID \
          --change-batch file://change-resource-record-sets.json

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

      - name: Setup After Start
        env:
          PUBLIC_IP: ${{ env.PUBLIC_IP }}
          EC2_NAME_AT_IP: ubuntu@${{ env.PUBLIC_IP }}
        run: |
          ssh -o StrictHostKeyChecking=no ${{ env.EC2_NAME_AT_IP }} 'mkdir -p ~/dev/doorfe'
          ssh -o StrictHostKeyChecking=no ${{ env.EC2_NAME_AT_IP }} "cd ${{vars.EC2_PROJECT_PATH}} && bash setup-ec2.bash start"
        timeout-minutes: 1
        continue-on-error: true
